export const EnumCity = [
    "São Paulo", 
    "Belo Horizonte",
    "Rio de Janeiro",
    "Porto Alegre",
    "Curitiba",
    "Campinas",
    "Recife",
    "Florianópolis",
    "Fortaleza",
    "Salvador",
    "Brasília",
    "Vitória", 
    "São José dos Campos",
    "Sorocaba", 
    "Joinville", 
    "Uberlândia",
    "Londrina",
    "Niterói",
    "Manaus", 
    "Ribeirão Preto",
    "Pelotas", 
    "Maringá",
    "Santos",
    "Juiz de Fora",
    "São José do Rio Preto",
    "Caxias do Sul",
    "Piracicaba",
    "Uberaba",
    "São Carlos",
    "Flamengo", 
    "Maceio"
]