export const EnumTech = [
    "Python",
    "Java",
    "Javascript",
    "C#",
    "C/C++",
    "PHP",
    "R",
    "TypeScript",
    "Objective-C",
    "Swift",
    "Malab",
    "Kotlin",
    "Go",
    "Rusty",
    "Rub",
    "VBA",
    "Ada",
    "Scala",
    "Visual Basic",
    "Dart",
    "Node.js",
    "Spring Boot",
    "Django",
    "Ruby on Rails",
    "React",
    "Angular",
    "Vue.js",
    "Django",
    "Spring",
    "Express.js",
    "Redux",
    "jQuery",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQL Server",
    "Oracle",
]